FROM nvidia/cuda:10.1-base-ubuntu16.04

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Install Miniconda and Python 3.6
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV PATH=/home/user/miniconda/bin:$PATH
RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda install -y python==3.6.9 \
 && conda clean -ya

# CUDA 10.1-specific steps
RUN conda install -y -c pytorch \
    cudatoolkit=10.1 \
    "pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0" \
    "torchvision=0.5.0=py36_cu101" \
    "numpy"
    "math"
    "matplotlib"
    "time"
    "copy"
    "warnings"
 && conda clean -ya

# Set the default command to python3
FROM python:3
WORKDIR ./experiments/
COPY . .
CMD ["science_model.py"]
ENTRYPOINT ["python3"]
